#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '*****************************'
echo '**** running lint-staged ****'
echo '*****************************'
yarn lint-staged
echo '******************************'
echo '**** lint-staged finished ****'
echo '******************************'



